# .github/workflows/publish.yml

name: Publish Python Package to PyPI

on:
  release:
    types: [published] # This workflow runs when a new GitHub Release is published

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: pypi # Refers to the environment name you set up in PyPI Trusted Publishers
    permissions:
      id-token: write # IMPORTANT: Required for Trusted Publishers
      contents: read # Required to checkout the code

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.8" # Use a specific Python version (e.g., '3.8', '3.9', '3.10', '3.11', '3.12')
          # Or if you use `python_requires` in setup.py, you can use:
          # python-version: ${{ matrix.python-version }} # if you have a matrix strategy

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel build twine

      - name: Build package
        run: python -m build # This creates your .whl and .tar.gz files in `dist/`

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        # No 'user' or 'password' needed if using Trusted Publishers
        # If not using Trusted Publishers, you'd use:
        # with:
        #   user: __token__
        #   password: ${{ secrets.PYPI_API_TOKEN }} # Set this in GitHub repository secrets
